### ISSUE TITLE
add new Artists in data.js

### ISSUE THREAD

**Issue by Gupta-Suruchi** [ashishalf/desirhyme#2]
Hi, I would like to add more Artists data in your application, Kindly assign this issue to me.

**Comment by heyashishsaini** [comment]
Yes, of course you can.

**Comment by heyashishsaini** [comment]
But the artists will be rappers only and from India or Pakistan.

**Comment by Gupta-Suruchi** [comment]
> But the artists will be rappers only and from India or Pakistan.

Yes sure, I'll keep that thing in mind.
